### ISSUE TITLE
Comentarios sin usuario

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/chotuve-app-server#36]
Creo yo con sin usuario no puede pasar, no se pueden eliminar usuarios
EL tema es si se deshabilita el usuario que hacer en esos casos. No estoy seguro si el auth sever te devuelve la info del usuario si este esta deshabilitado, no se bien que cual es la idea si solo no puede entrar o nadie pueda ver nada de ese usuario. Como la consigna no lo dice, yo haria lo mas facil que es que no pueda entrar pero todo lo que ya tiene queda igual, a menos que tambien se deshabiliten sus videos por ejemplo

**Comment by FrancoLiberali** [comment]
Lo mencione en el pr pero ya quedo en el olvido, poner <eliminado> en el autor va a romper la app

**Comment by edjus** [comment]
El usuario debería tener un campo de habilitado, que se usa justamente desde el web admin. También me parece más sencillo el camino de que no pueda entrar y ya, de otra manera tendría que habilitarse un endpoint en el media para que desde el web admin se habilite/deshabilite los videos de un usuario.

**Comment by sportelliluciano** [comment]
```
+        autores = {u['id']: u
+                   for u in auth_server_api.obtener_usuarios(params).json()}
+
+        return [{
+            'autor': autores.get(comentario.usuario, USUARIO_ELIMINADO),
```
> esto probablemente haga que se rompa la app, el comentario necesita tener la info de su autor. Igual nada esto de que el usuario se alla eliminado no existe y tendriamos que ver bien como hacerlo para deshabilitado. Creo issue

No sería muy dificil controlar esto desde el modelo de la App. Simplemente que cree un Usuario con nombre <eliminado> o que devuelva un nullable y el presentador convierta ese null en '<eliminado>'.

**Comment by sportelliluciano** [comment]
Resolución: Los comentarios de los usuarios deshabilitados van a seguir estando. Siempre trae usuarios (deshabilitados vienen con un campo "habilitado" = false que será ignorado).
