### ISSUE TITLE
Agarrar las variables de entorno FLASK_ENV

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/chotuve-app-server#8]
ya esta seteada en heroku

**Comment by sportelliluciano** [comment]
No entiendo este issue (creo que lo hablamos pero no me acuerdo), quién debería agarrar la variable de entorno? El Dockerfile productivo? Para qué sería esto?

**Comment by sportelliluciano** [comment]
Esto no hace falta.
